[tool.poetry]
name = "mnemosyne"
version = "0.1.0"
description = "AI Assistant CLI for multi-agent orchestration and memory-driven automation"
authors = ["Surya Narayanaa N T  <suryanarayanaant@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
mnemo = "mnemosyne.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.12.0"
rich = "^13.0.0"
textual = "^0.50.0"
langchain = "^0.1.0"
langgraph = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"