[tool.poetry]
name = "mnemosyne"
version = "0.1.0"
description = "AI Assistant CLI for multi-agent orchestration and memory-driven automation"
authors = ["Surya Narayanaa N T  <suryanarayanaant@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
mnemo = "mnemosyne.main:app"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.17.4"
rich = "^14.1.0"
textual = "^6.1.0"
langchain = "^0.3.27"
langgraph = "^0.6.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"